// <auto-generated />
using System;
using DotnetAuth.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProjectBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260126074114_AddUserActivity")]
    partial class AddUserActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectBackend.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenEmpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProjectBackend.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Two imprisoned men form a deep bond over decades, finding hope and redemption through quiet resilience.",
                            Director = "Frank Darabont",
                            Genre = "Drama",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
                            Rating = 9.3000000000000007,
                            Title = "The Shawshank Redemption",
                            TrailerUrl = "https://www.youtube.com/embed/6hB3S9bIaco",
                            Year = 1994
                        },
                        new
                        {
                            Id = 2,
                            Description = "The patriarch of a powerful crime family hands control to his reluctant son, drawing him into a ruthless world.",
                            Director = "Francis Ford Coppola",
                            Genre = "Crime",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
                            Rating = 9.1999999999999993,
                            Title = "The Godfather",
                            TrailerUrl = "https://www.youtube.com/embed/sY1S34973zA",
                            Year = 1972
                        },
                        new
                        {
                            Id = 3,
                            Description = "Batman faces the Joker, a criminal mastermind who seeks to plunge Gotham into chaos.",
                            Director = "Christopher Nolan",
                            Genre = "Action",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                            Rating = 9.0,
                            Title = "The Dark Knight",
                            TrailerUrl = "https://www.youtube.com/embed/EXeTwQWrcwY",
                            Year = 2008
                        },
                        new
                        {
                            Id = 4,
                            Description = "Interconnected stories of crime, violence, and redemption unfold in Los Angeles.",
                            Director = "Quentin Tarantino",
                            Genre = "Crime",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/fIE3lAGcZDV1G6XM5KmuWnNsPp1.jpg",
                            Rating = 8.9000000000000004,
                            Title = "Pulp Fiction",
                            TrailerUrl = "https://www.youtube.com/embed/s7EdQ4FqbhY",
                            Year = 1994
                        },
                        new
                        {
                            Id = 5,
                            Description = "The final battle for Middle-earth begins as Frodo and Sam approach Mount Doom.",
                            Director = "Peter Jackson",
                            Genre = "Fantasy",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
                            Rating = 8.9000000000000004,
                            Title = "The Lord of the Rings: The Return of the King",
                            TrailerUrl = "https://www.youtube.com/embed/r5X-hFf6Bwo",
                            Year = 2003
                        },
                        new
                        {
                            Id = 6,
                            Description = "A simple man experiences extraordinary moments while pursuing his lifelong love.",
                            Director = "Robert Zemeckis",
                            Genre = "Drama",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
                            Rating = 8.8000000000000007,
                            Title = "Forrest Gump",
                            TrailerUrl = "https://www.youtube.com/embed/bLvqoHBptjg",
                            Year = 1994
                        },
                        new
                        {
                            Id = 7,
                            Description = "An insomniac office worker creates a secret fight club that spirals into chaos.",
                            Director = "David Fincher",
                            Genre = "Drama",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg",
                            Rating = 8.8000000000000007,
                            Title = "Fight Club",
                            TrailerUrl = "https://www.youtube.com/embed/SUXWAEX2jlg",
                            Year = 1999
                        },
                        new
                        {
                            Id = 8,
                            Description = "A skilled thief enters dreams to steal secrets, risking reality itself.",
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
                            Rating = 8.6999999999999993,
                            Title = "Inception",
                            TrailerUrl = "https://www.youtube.com/embed/YoHD9XEInc0",
                            Year = 2010
                        },
                        new
                        {
                            Id = 9,
                            Description = "A hacker learns reality is a simulation and joins a rebellion against its creators.",
                            Director = "The Wachowskis",
                            Genre = "Sci-Fi",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
                            Rating = 8.6999999999999993,
                            Title = "The Matrix",
                            TrailerUrl = "https://www.youtube.com/embed/vKQi3bBA1y8",
                            Year = 1999
                        },
                        new
                        {
                            Id = 10,
                            Description = "The rise and fall of a gangster living life on the edge.",
                            Director = "Martin Scorsese",
                            Genre = "Crime",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
                            Rating = 8.6999999999999993,
                            Title = "Goodfellas",
                            TrailerUrl = "https://www.youtube.com/embed/qo5jJpHtI1Y",
                            Year = 1990
                        },
                        new
                        {
                            Id = 11,
                            Description = "Two detectives hunt a serial killer who uses the seven deadly sins as his motive.",
                            Director = "David Fincher",
                            Genre = "Thriller",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg",
                            Rating = 8.5999999999999996,
                            Title = "Se7en",
                            TrailerUrl = "https://www.youtube.com/embed/znmZoVkCjpI",
                            Year = 1995
                        },
                        new
                        {
                            Id = 12,
                            Description = "Explorers travel through space to save humanity from extinction.",
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
                            Rating = 8.5999999999999996,
                            Title = "Interstellar",
                            TrailerUrl = "https://www.youtube.com/embed/zSWdZVtXT7E",
                            Year = 2014
                        },
                        new
                        {
                            Id = 13,
                            Description = "An FBI trainee seeks help from a brilliant cannibal to catch a serial killer.",
                            Director = "Jonathan Demme",
                            Genre = "Thriller",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
                            Rating = 8.5999999999999996,
                            Title = "The Silence of the Lambs",
                            TrailerUrl = "https://www.youtube.com/embed/W6Mm8Sbe__o",
                            Year = 1991
                        },
                        new
                        {
                            Id = 14,
                            Description = "A group of soldiers search for a paratrooper behind enemy lines during WWII.",
                            Director = "Steven Spielberg",
                            Genre = "War",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg",
                            Rating = 8.5999999999999996,
                            Title = "Saving Private Ryan",
                            TrailerUrl = "https://www.youtube.com/embed/9CiW_DgxCnQ",
                            Year = 1998
                        },
                        new
                        {
                            Id = 15,
                            Description = "The rise of organized crime in Rio de Janeiro’s most dangerous neighborhood.",
                            Director = "Fernando Meirelles",
                            Genre = "Crime",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg",
                            Rating = 8.5999999999999996,
                            Title = "City of God",
                            TrailerUrl = "https://www.youtube.com/embed/dcUOO4Itgmw",
                            Year = 2002
                        },
                        new
                        {
                            Id = 16,
                            Description = "A death row guard encounters a mysterious inmate with supernatural abilities.",
                            Director = "Frank Darabont",
                            Genre = "Drama",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg",
                            Rating = 8.5999999999999996,
                            Title = "The Green Mile",
                            TrailerUrl = "https://www.youtube.com/embed/Ki4haFrqSrw",
                            Year = 1999
                        },
                        new
                        {
                            Id = 17,
                            Description = "A poor family infiltrates a wealthy household with unexpected consequences.",
                            Director = "Bong Joon-ho",
                            Genre = "Thriller",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
                            Rating = 8.5,
                            Title = "Parasite",
                            TrailerUrl = "https://www.youtube.com/embed/SEUXfv87Wpk",
                            Year = 2019
                        },
                        new
                        {
                            Id = 18,
                            Description = "A hitman forms an unlikely bond with a young girl seeking revenge.",
                            Director = "Luc Besson",
                            Genre = "Action",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/yI6X2cCM5YPJtxMhUd3dPGqDAhw.jpg",
                            Rating = 8.5,
                            Title = "Léon: The Professional",
                            TrailerUrl = "https://www.youtube.com/embed/jawVxq1Iyl0",
                            Year = 1994
                        },
                        new
                        {
                            Id = 19,
                            Description = "A betrayed general seeks vengeance in the Roman arena.",
                            Director = "Ridley Scott",
                            Genre = "Action",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
                            Rating = 8.5,
                            Title = "Gladiator",
                            TrailerUrl = "https://www.youtube.com/embed/owK1qxDselE",
                            Year = 2000
                        },
                        new
                        {
                            Id = 20,
                            Description = "A young drummer pushes himself to the limit under a ruthless instructor.",
                            Director = "Damien Chazelle",
                            Genre = "Drama",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/6uSPcdGJAkF6P5kP1K9z5i2nV8p.jpg",
                            Rating = 8.5,
                            Title = "Whiplash",
                            TrailerUrl = "https://www.youtube.com/embed/7d_jQycdQGo",
                            Year = 2014
                        },
                        new
                        {
                            Id = 21,
                            Description = "Two rival magicians engage in a deadly competition that pushes obsession to the extreme.",
                            Director = "Christopher Nolan",
                            Genre = "Drama",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/5MXyQfz8xUP3dIFPTubhTsbFY6N.jpg",
                            Rating = 8.5,
                            Title = "The Prestige",
                            TrailerUrl = "https://www.youtube.com/embed/o4gHCmTQDVI",
                            Year = 2006
                        },
                        new
                        {
                            Id = 22,
                            Description = "An undercover cop and a mole in the police attempt to uncover each other's identities.",
                            Director = "Martin Scorsese",
                            Genre = "Crime",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeqJ6K94mEZM1.jpg",
                            Rating = 8.5,
                            Title = "The Departed",
                            TrailerUrl = "https://www.youtube.com/embed/iojhqm0JTW4",
                            Year = 2006
                        },
                        new
                        {
                            Id = 23,
                            Description = "A Jewish pianist struggles to survive the horrors of World War II in occupied Poland.",
                            Director = "Roman Polanski",
                            Genre = "Drama",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
                            Rating = 8.5,
                            Title = "The Pianist",
                            TrailerUrl = "https://www.youtube.com/embed/BFwGqLa_oAo",
                            Year = 2002
                        },
                        new
                        {
                            Id = 24,
                            Description = "A young lion prince must reclaim his rightful place as king after tragedy strikes.",
                            Director = "Roger Allers",
                            Genre = "Animation",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg",
                            Rating = 8.5,
                            Title = "The Lion King",
                            TrailerUrl = "https://www.youtube.com/embed/4sj1MT05lAA",
                            Year = 1994
                        },
                        new
                        {
                            Id = 25,
                            Description = "A cyborg is sent back in time to protect humanity's future leader.",
                            Director = "James Cameron",
                            Genre = "Sci-Fi",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/5M0j0B18abtBI5gi2RhfjjurTqb.jpg",
                            Rating = 8.5,
                            Title = "Terminator 2: Judgment Day",
                            TrailerUrl = "https://www.youtube.com/embed/CRRlbK5w8AE",
                            Year = 1991
                        },
                        new
                        {
                            Id = 26,
                            Description = "A teenager travels back in time and must ensure his parents fall in love.",
                            Director = "Robert Zemeckis",
                            Genre = "Sci-Fi",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/pTpxQB1N0waaSc3OSn0e9oc8kx9.jpg",
                            Rating = 8.5,
                            Title = "Back to the Future",
                            TrailerUrl = "https://www.youtube.com/embed/qvsgGtivCgs",
                            Year = 1985
                        },
                        new
                        {
                            Id = 27,
                            Description = "A former neo-Nazi tries to prevent his younger brother from following the same path.",
                            Director = "Tony Kaye",
                            Genre = "Drama",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/c2gsmSQ2Cqv8zosqKOCwRS0GFBS.jpg",
                            Rating = 8.5,
                            Title = "American History X",
                            TrailerUrl = "https://www.youtube.com/embed/XfQYHqsiN5g",
                            Year = 1998
                        },
                        new
                        {
                            Id = 28,
                            Description = "A con man recounts the story of a legendary criminal mastermind.",
                            Director = "Bryan Singer",
                            Genre = "Crime",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/bUPmtQzrRhzqYySeiMpv7GurAfm.jpg",
                            Rating = 8.5,
                            Title = "The Usual Suspects",
                            TrailerUrl = "https://www.youtube.com/embed/oiXdPolca5w",
                            Year = 1995
                        },
                        new
                        {
                            Id = 29,
                            Description = "A young girl enters a magical world ruled by spirits and strange creatures.",
                            Director = "Hayao Miyazaki",
                            Genre = "Animation",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
                            Rating = 8.5999999999999996,
                            Title = "Spirited Away",
                            TrailerUrl = "https://www.youtube.com/embed/ByXuk9QqQkk",
                            Year = 2001
                        },
                        new
                        {
                            Id = 30,
                            Description = "An unlikely friendship forms between a quadriplegic man and his caretaker.",
                            Director = "Olivier Nakache",
                            Genre = "Comedy",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/4mFsNQwbD0F237Tx7gAPotd0nbJ.jpg",
                            Rating = 8.5,
                            Title = "The Intouchables",
                            TrailerUrl = "https://www.youtube.com/embed/34WIbmXkewU",
                            Year = 2011
                        },
                        new
                        {
                            Id = 31,
                            Description = "A factory worker struggles to survive in an increasingly industrialized society.",
                            Director = "Charlie Chaplin",
                            Genre = "Comedy",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/7u0aYf8E3a2RZkHcZ9zH8fF2A3I.jpg",
                            Rating = 8.5,
                            Title = "Modern Times",
                            TrailerUrl = "https://www.youtube.com/embed/GLeDdzGUTq0",
                            Year = 1936
                        },
                        new
                        {
                            Id = 32,
                            Description = "A woman checks into a secluded motel where dark secrets lurk.",
                            Director = "Alfred Hitchcock",
                            Genre = "Horror",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/81d8oyEFgj7FlxJqSDXWr8JH8kV.jpg",
                            Rating = 8.5,
                            Title = "Psycho",
                            TrailerUrl = "https://www.youtube.com/embed/Wz719b9QUqY",
                            Year = 1960
                        },
                        new
                        {
                            Id = 33,
                            Description = "A mysterious stranger aids a widow in protecting her land from ruthless criminals.",
                            Director = "Sergio Leone",
                            Genre = "Western",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/9uGHEgsiUXjCNq8wdq4r49YL8A1.jpg",
                            Rating = 8.5,
                            Title = "Once Upon a Time in the West",
                            TrailerUrl = "https://www.youtube.com/embed/ojrVbm5p-UE",
                            Year = 1968
                        },
                        new
                        {
                            Id = 34,
                            Description = "A nightclub owner must choose between love and sacrifice during World War II.",
                            Director = "Michael Curtiz",
                            Genre = "Romance",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/5K7cOHoay2mZusSLezBOY0Qxh8a.jpg",
                            Rating = 8.5,
                            Title = "Casablanca",
                            TrailerUrl = "https://www.youtube.com/embed/BkL9l7qovsE",
                            Year = 1942
                        },
                        new
                        {
                            Id = 35,
                            Description = "A tramp falls in love with a blind flower girl and tries to change her life.",
                            Director = "Charlie Chaplin",
                            Genre = "Comedy",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/uZBW2Gf8r8y2UP2Y4Wf0xZPjQzN.jpg",
                            Rating = 8.5,
                            Title = "City Lights",
                            TrailerUrl = "https://www.youtube.com/embed/7vl7F8S4cpQ",
                            Year = 1931
                        },
                        new
                        {
                            Id = 36,
                            Description = "A family becomes trapped in a haunted hotel during winter isolation.",
                            Director = "Stanley Kubrick",
                            Genre = "Horror",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/9fgh3Ns1iRzlQNYuJyK0ARQZU7w.jpg",
                            Rating = 8.4000000000000004,
                            Title = "The Shining",
                            TrailerUrl = "https://www.youtube.com/embed/5Cb3ik6zP2I",
                            Year = 1980
                        },
                        new
                        {
                            Id = 37,
                            Description = "Earth's mightiest heroes unite to stop a powerful cosmic threat.",
                            Director = "Anthony Russo",
                            Genre = "Action",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
                            Rating = 8.4000000000000004,
                            Title = "Avengers: Infinity War",
                            TrailerUrl = "https://www.youtube.com/embed/6ZfuNTqbHE8",
                            Year = 2018
                        },
                        new
                        {
                            Id = 38,
                            Description = "The Avengers make one final stand to restore balance to the universe.",
                            Director = "Anthony Russo",
                            Genre = "Action",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
                            Rating = 8.4000000000000004,
                            Title = "Avengers: Endgame",
                            TrailerUrl = "https://www.youtube.com/embed/TcMBFSGVi1c",
                            Year = 2019
                        },
                        new
                        {
                            Id = 39,
                            Description = "A failed comedian descends into madness, becoming Gotham's infamous villain.",
                            Director = "Todd Phillips",
                            Genre = "Drama",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
                            Rating = 8.4000000000000004,
                            Title = "Joker",
                            TrailerUrl = "https://www.youtube.com/embed/zAGVQLHvwOY",
                            Year = 2019
                        },
                        new
                        {
                            Id = 40,
                            Description = "Two strangers mysteriously swap bodies across time and space.",
                            Director = "Makoto Shinkai",
                            Genre = "Animation",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg",
                            Rating = 8.4000000000000004,
                            Title = "Your Name",
                            TrailerUrl = "https://www.youtube.com/embed/xU47nhruN-Q",
                            Year = 2016
                        },
                        new
                        {
                            Id = 41,
                            Description = "A boy journeys into the Land of the Dead to uncover his family's past.",
                            Director = "Lee Unkrich",
                            Genre = "Animation",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
                            Rating = 8.4000000000000004,
                            Title = "Coco",
                            TrailerUrl = "https://www.youtube.com/embed/Ga6RYejo6Hk",
                            Year = 2017
                        },
                        new
                        {
                            Id = 42,
                            Description = "A freed slave sets out to rescue his wife with the help of a bounty hunter.",
                            Director = "Quentin Tarantino",
                            Genre = "Western",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
                            Rating = 8.4000000000000004,
                            Title = "Django Unchained",
                            TrailerUrl = "https://www.youtube.com/embed/eUdM9vrCbow",
                            Year = 2012
                        },
                        new
                        {
                            Id = 43,
                            Description = "A stockbroker rises to extreme wealth through corruption and excess.",
                            Director = "Martin Scorsese",
                            Genre = "Biography",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/pWHf4khOloNVfCxscsXFj3jj6gP.jpg",
                            Rating = 8.4000000000000004,
                            Title = "The Wolf of Wall Street",
                            TrailerUrl = "https://www.youtube.com/embed/iszwuX1AK6A",
                            Year = 2013
                        },
                        new
                        {
                            Id = 44,
                            Description = "A man seeks revenge after being imprisoned for years without explanation.",
                            Director = "Park Chan-wook",
                            Genre = "Thriller",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg",
                            Rating = 8.4000000000000004,
                            Title = "Oldboy",
                            TrailerUrl = "https://www.youtube.com/embed/2HkjrJ6IK5E",
                            Year = 2003
                        },
                        new
                        {
                            Id = 45,
                            Description = "A young warrior becomes involved in a conflict between nature and industry.",
                            Director = "Hayao Miyazaki",
                            Genre = "Animation",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/jHWmNr7m544fJ8eItsfNk8fs2Ed.jpg",
                            Rating = 8.4000000000000004,
                            Title = "Princess Mononoke",
                            TrailerUrl = "https://www.youtube.com/embed/4OiMOHRDs14",
                            Year = 1997
                        },
                        new
                        {
                            Id = 46,
                            Description = "A man slowly discovers his entire life is a televised reality show.",
                            Director = "Peter Weir",
                            Genre = "Drama",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/vuza0WqY239yBXOadKlGwJsZJFE.jpg",
                            Rating = 8.1999999999999993,
                            Title = "The Truman Show",
                            TrailerUrl = "https://www.youtube.com/embed/dlnmQbPGuls",
                            Year = 1998
                        },
                        new
                        {
                            Id = 47,
                            Description = "A new blade runner uncovers a secret that could destabilize society.",
                            Director = "Denis Villeneuve",
                            Genre = "Sci-Fi",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/aMpyrCizvSdc0UIMblJ1srVgAEF.jpg",
                            Rating = 8.0,
                            Title = "Blade Runner 2049",
                            TrailerUrl = "https://www.youtube.com/embed/gCcx85zbxz4",
                            Year = 2017
                        },
                        new
                        {
                            Id = 48,
                            Description = "A hotel concierge and his protégé become entangled in a bizarre adventure.",
                            Director = "Wes Anderson",
                            Genre = "Comedy",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
                            Rating = 8.0999999999999996,
                            Title = "The Grand Budapest Hotel",
                            TrailerUrl = "https://www.youtube.com/embed/1Fg5iWmQjwk",
                            Year = 2014
                        },
                        new
                        {
                            Id = 49,
                            Description = "A violent youth undergoes controversial psychological conditioning.",
                            Director = "Stanley Kubrick",
                            Genre = "Crime",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/4sHeTAp65WrSSuc05nRBKddhBxO.jpg",
                            Rating = 8.3000000000000007,
                            Title = "A Clockwork Orange",
                            TrailerUrl = "https://www.youtube.com/embed/T54uZPI4Z8A",
                            Year = 1971
                        },
                        new
                        {
                            Id = 50,
                            Description = "Four lives spiral into addiction and despair in haunting fashion.",
                            Director = "Darren Aronofsky",
                            Genre = "Drama",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/nOd6vjEmzCT0k4VYqsA2hwyi87C.jpg",
                            Rating = 8.3000000000000007,
                            Title = "Requiem for a Dream",
                            TrailerUrl = "https://www.youtube.com/embed/jzk-lmU4KZ4",
                            Year = 2000
                        });
                });

            modelBuilder.Entity("ProjectBackend.Domain.Entities.ProjectBackend.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ProjectBackend.Domain.Entities.UserActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProjectBackend.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProjectBackend.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectBackend.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProjectBackend.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
